require:
  - ./lib/rubocop/cop/internal_affairs/debug

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'lib/htimlee/tokenizer/named_character.rb'
    - 'tmp/**/*.rb'

InternalAffairs/Debug:
  Enabled: true

Layout/LineLength:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 100

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/YodaCondition:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/AsciiComments:
  Enabled: false
